version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: persondb
      MYSQL_USER: personuser
      MYSQL_PASSWORD: personpass
    ports:
      - "3306:3306"

  personapi:
    build: .
    container_name: personapi-container
    depends_on:
      - mysql
    ports:
      - "8082:8080"